### ISSUE TITLE
The 'Report Issues' button redirects here

### ISSUE THREAD

**Issue by james-carton** [bigbadweb/otcw-issues#4]
https://github.com/bigbadweb/otcw-issues/issues

It's a bit jarring for the user to be redirected out of the website to Github and not user friendly for the majority of people who haven't a clue of what Github is. Suggestion to provide a simple contact form within the website.

**Comment by mattstabeler** [comment]
Better to report them here @james-carton https://github.com/bigbadweb/otcwapp
